INSERT INTO CPUBrand (name) VALUES ('Intel');
INSERT INTO CPUBrand (name) VALUES ('AMD');
INSERT INTO CPUBrand (name) VALUES ('Apple');
INSERT INTO CPUBrand (name) VALUES ('Qualcomm');
INSERT INTO CPUBrand (name) VALUES ('ARM');
INSERT INTO CPUBrand (name) VALUES ('Cyrix');
INSERT INTO CPUBrand (name) VALUES ('IBM');
INSERT INTO CPUBrand (name) VALUES ('Motorola');
INSERT INTO CPUBrand (name) VALUES ('Sun Microsystems');
INSERT INTO CPUBrand (name) VALUES ('DEC');
INSERT INTO CPUBrand (name) VALUES ('Transmeta');
INSERT INTO CPUBrand (name) VALUES ('VIA Technologies');
INSERT INTO CPUBrand (name) VALUES ('Rise Technology');
INSERT INTO CPUBrand (name) VALUES ('IDT');
INSERT INTO CPUBrand (name) VALUES ('NexGen');
INSERT INTO CPUBrand (name) VALUES ('Centaur Technology');
INSERT INTO CPUBrand (name) VALUES ('Zilog');
INSERT INTO CPUBrand (name) VALUES ('National Semiconductor');
INSERT INTO CPUBrand (name) VALUES ('Texas Instruments');
INSERT INTO CPUBrand (name) VALUES ('NEC');
INSERT INTO CPUBrand (name) VALUES ('Fujitsu');
INSERT INTO CPUBrand (name) VALUES ('Hitachi');
INSERT INTO CPUBrand (name) VALUES ('Toshiba');
INSERT INTO CPUBrand (name) VALUES ('Sony');
INSERT INTO CPUBrand (name) VALUES ('Samsung');
INSERT INTO CPUBrand (name) VALUES ('NVIDIA');
INSERT INTO CPUBrand (name) VALUES ('Broadcom');
INSERT INTO CPUBrand (name) VALUES ('Marvell');
INSERT INTO CPUBrand (name) VALUES ('Rockchip');
INSERT INTO CPUBrand (name) VALUES ('Allwinner');
INSERT INTO CPUBrand (name) VALUES ('MediaTek');
INSERT INTO CPUBrand (name) VALUES ('Huawei');
INSERT INTO CPUBrand (name) VALUES ('HiSilicon');
INSERT INTO CPUBrand (name) VALUES ('Spreadtrum');
INSERT INTO CPUBrand (name) VALUES ('Xilinx');
INSERT INTO CPUBrand (name) VALUES ('Altera');
INSERT INTO CPUBrand (name) VALUES ('Infineon');
INSERT INTO CPUBrand (name) VALUES ('STMicroelectronics');
INSERT INTO CPUBrand (name) VALUES ('Renesas');
INSERT INTO CPUBrand (name) VALUES ('Imagination Technologies');
INSERT INTO CPUBrand (name) VALUES ('SiS');
INSERT INTO CPUBrand (name) VALUES ('ULi Electronics');
INSERT INTO CPUBrand (name) VALUES ('Geode');