services:
  benchmarkinator-db:
    image: mysql:8.0
    container_name: benchmarkinator-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: benchmarkinator
      MYSQL_USER: benchmarkinator
      MYSQL_PASSWORD: benchmarkinatorpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root" ]
      interval: 10s
      timeout: 5s
      retries: 10

  benchmarkinator-api:
    build: .
    container_name: benchmarkinator-api
    environment:
      DATABASE_URL: mysql+pymysql://benchmarkinator:benchmarkinatorpassword@benchmarkinator-db:3306/benchmarkinator
    ports:
      - "12345:12345"
    depends_on:
      benchmarkinator-db:
        condition: service_healthy
    entrypoint: [ "/app/wait-for-it.sh", "benchmarkinator-db:3306", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "12345" ]

volumes:
  mysql_data: