services:
  benchmarkinator-db:
    image: mysql:8.4
    container_name: benchmarkinator-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root" ]
      interval: 10s
      timeout: 5s
      retries: 10

  benchmarkinator-api:
    build: .
    image: rootifera/benchmarkinator-api
    container_name: benchmarkinator-api
    environment:
      DATABASE_URL: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@benchmarkinator-db:${MYSQL_PORT}/${MYSQL_DATABASE}"
      API_KEY: ${API_KEY}
    ports:
      - "${API_PORT}:12345"
    depends_on:
      benchmarkinator-db:
        condition: service_healthy
    entrypoint:
      [ "/app/wait-for-it.sh", "benchmarkinator-db:${MYSQL_PORT}", "--",
        "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "12345" ]
    pull_policy: never

  benchmarkinator-webui:
    build:
      context: ./webui
      args:
        WEBADMIN: ${WEBADMIN}
        WEBPASSWORD: ${WEBPASSWORD}
        API_KEY: ${API_KEY}
    image: rootifera/benchmarkinator-webui
    container_name: benchmarkinator-webui
    ports:
      - "4000:80"
    depends_on:
      benchmarkinator-api:
        condition: service_started
    environment:
      NODE_ENV: production
    pull_policy: never

volumes:
  mysql_data:
